inputs:
  targets:
    required: false
  components:
    required: false

runs:
  using: composite
  steps:
    - id: read-rust-toolchain
      run: echo "toolchain=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.read-rust-toolchain.outputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
